import Foundation
func managementStateTests() throws {
    var state = ManagementState()
    try check(state.section == .general && state.lifecycle == .starting, "initial management")
    state.select(.memory); state.refresh(.idle)
    try check(state.section == .memory && state.lifecycle == .ready, "navigation survives readiness")
    try check(!state.voiceAvailable && state.canShowCompanion, "engine readiness never enables voice")
    state.refresh(.unavailable); state.refresh(.idle)
    try check(state.lifecycle == .unavailable && state.canNavigate, "failure rejects stale readiness")
    state.refresh(.stopped); state.refresh(.unavailable); state.select(.models)
    try check(state.lifecycle == .stopping && !state.canNavigate && state.section == .memory, "stop is terminal")
    try check(ManagementSection.allCases.count == 11, "complete navigation")
    var plugins = ManagementState(); plugins.select(.plugins)
    try check(!plugins.description.contains("has not queried an installed plugin inventory") && plugins.description.contains("closed local catalog"), "plugins inventory-backed")
    var connections = ManagementState(); connections.select(.connections)
    try check(!connections.description.contains("has not queried") && connections.description.contains("closed local catalog") && connections.description.contains("Connection save is not a grant") && connections.description.contains("GitHub"), "connections inventory-backed")
    plugins.select(.permissions)
    try check(!plugins.description.contains("Allow Always") && plugins.description.contains("Allow Once") && plugins.description.contains("mounted compatible plugin") && plugins.description.contains("Ask-each-time") && plugins.description.contains("Open URL") && plugins.description.contains("Accessibility") && plugins.description.contains("local time") && plugins.description.contains("Connection save is not a grant") && plugins.description.contains("MCP"), "permissions ask for 09 tools and mounted MCP; 15/16 stay unavailable")
    var models = ManagementState(); models.select(.models)
    try check(models.description.contains("hardware") && models.description.contains("Recommended") && models.description.contains("speech headroom") && !models.description.contains("No downloads or hardware recommendations"), "models onboarding copy")
    var pets = ManagementState(); pets.select(.pets)
    try check(pets.description.contains("Wisp orb") && pets.description.contains("Fox") && pets.description.contains("Robot") && pets.description.contains("same Wisp") && !pets.description.contains("body selection are unavailable") && !pets.description.contains("Additional bodies and body selection are unavailable"), "pets inventory-backed")
    var skills = ManagementState(); skills.select(.skills)
    try check(skills.description.contains("has not queried"), "skills still has not queried inventory")
    var diag = ManagementState(); diag.select(.diagnostics)
    try check(diag.description.contains("hardware snapshot") && !diag.description.contains("BEGIN") && !diag.description.contains("sk-") && diag.description.contains("never include credentials"), "diagnostics omit secrets")
}
