import { it, expect } from 'vitest';
import { Context } from '@deepseek-ai/cordis';
import { Session, SessionId, SessionSeq } from '@deepseek-ai/dsh-session';
import type { Agent } from '@deepseek-ai/dsh-agent';
import { ToolCallId } from '@deepseek-ai/dsh-llm';
import ToolRuntime from '@deepseek-ai/dsh-tools';
import SystemPrompt from '@deepseek-ai/dsh-system-prompt';
import ApprovalService from '@deepseek-ai/dsh-user-approval';
import { PermissionPolicy, decisionFor } from '../../engine/approval-policy.ts';

async function fixture(deadline=1000) {
 const ctx=new Context();await ctx.plugin(SystemPrompt);await ctx.plugin(ToolRuntime);await ctx.plugin(ApprovalService);
 const session=Session.create(SessionId('owned'));session.append('turn/start',{turn:1});
 // Only identity carriers are minimal here. Separate live tests use actual parent/child agents.
 const controllers:AbortController[]=[];const agent={session,cancel:()=>controllers.forEach(c=>c.abort())} as unknown as Agent,frames:any[]=[],effects:any[]=[];
 const policy=new PermissionPolicy(ctx,{companionId:'11111111-1111-4111-8111-111111111111',generation:'22222222-2222-4222-8222-222222222222'},e=>e.agent===agent,(method,params)=>frames.push({method,params}),deadline);
 let destination='isolated-ledger';
 const definition={name:'wisp_permission_check',description:'test',parameters:{},output:{schema:{type:'string' as const},render:()=>[{type:'text' as const,text:'done'}]},execute:async(args:any,exec:any)=>{policy.consume(exec);effects.push(args);return 'done';}};
 const unregister=ctx.tools.register(definition);
 policy.admit(definition,{source:'wisp-direct',revision:'1',describe:args=>{if(!args||Object.keys(args).join()!=='label'||!/^[a-z]{1,20}$/.test(args.label))throw Error('invalid');return {operation:'append-test-record',destination,fields:[{label:'Label',value:args.label}]};}});
 const stopAnswering=policy.install();policy.seal();
 const invoke=(id='c1',label='hello',overrides:any={},fact:any={})=>{
  const c=new AbortController();controllers.push(c);
  session.append('tool/call',{turn:1,step:1,callId:ToolCallId(id),name:definition.name,arguments:JSON.stringify({label}),...fact});
  return {c,result:ctx.tools.execute({callId:ToolCallId(id),name:definition.name,arguments:{label},agent,signal:c.signal,...overrides})};
 };
 const request=async(n=1)=>{for(let i=0;i<200;i++){const list=frames.filter(f=>f.method==='wisp.approval.requested');if(list.length>=n)return list[n-1].params;await new Promise(r=>setTimeout(r,1));}throw Error('request missing');};
 const audit=()=>Array.from({length:session.seq},(_,i)=>session.eventAt(SessionSeq(i)));
 return {ctx,agent,session,policy,stopAnswering,definition,unregister,frames,effects,invoke,request,audit,target:(value:string)=>{destination=value},close:async()=>{policy.cancel();await ctx.fiber.dispose();}};
}
it('withholding and exact one-shot grant; replay and second call cannot reuse it',async()=>{const f=await fixture();try{const c=f.invoke(),p=await f.request();expect(f.effects).toHaveLength(0);f.policy.decide(decisionFor(p,'allow-once'));expect((await c.result).isError).toBe(false);expect(f.effects).toHaveLength(1);expect(()=>f.policy.decide(decisionFor(p,'allow-once'))).toThrow();const next=f.invoke('c2'),p2=await f.request(2);expect(p2.requestId).not.toBe(p.requestId);f.policy.decide(decisionFor(p2,'deny'));await next.result;expect(f.effects).toHaveLength(1);}finally{await f.close();}});
for(const outcome of ['deny','cancel'])it(`${outcome} leaves no body entry and a paired real audit`,async()=>{const f=await fixture();try{const c=f.invoke(),p=await f.request();f.policy.decide(decisionFor(p,outcome));expect((await c.result).isError).toBe(true);expect(f.effects).toHaveLength(0);const asked=f.audit().find(e=>e?.type==='approval/asked')!;expect(f.audit().find(e=>e?.type==='approval/decided')).toMatchObject({data:{id:asked.data.id,outcome:outcome==='deny'?'rejected':'cancelled'}});}finally{await f.close();}});
for(const key of ['version','generation','requestId','sessionId','callId','actionDigest','decision'])it(`rejects wrong decision ${key}`,async()=>{const f=await fixture();try{const c=f.invoke(),p=await f.request();expect(()=>f.policy.decide({...decisionFor(p,'allow-once'),[key]:'wrong'})).toThrow();f.policy.cancel();await c.result;expect(f.effects).toHaveLength(0);}finally{await f.close();}});
it('mandatory guard denies an earlier allow listener',async()=>{const f=await fixture();try{f.ctx.on('tools/pre-execute',async()=>({kind:'allow' as const}),{prepend:true});expect((await f.invoke().result).isError).toBe(true);expect(f.effects).toHaveLength(0);}finally{await f.close();}});
for(const timing of ['pending','after-guard'])it(`registration replacement ${timing} cannot enter rogue body`,async()=>{const f=await fixture();try{const replace=()=>{f.unregister();f.ctx.tools.register({...f.definition,execute:async()=>{f.effects.push('ROGUE');return 'done';}});};if(timing==='after-guard')f.ctx.on('tools/execute',async(exec,next)=>{replace();return next();});const c=f.invoke(),p=await f.request();if(timing==='pending'){replace();expect(()=>f.policy.decide(decisionFor(p,'allow-once'))).toThrow();}else f.policy.decide(decisionFor(p,'allow-once'));expect((await c.result).isError).toBe(true);expect(c.c.signal.aborted).toBe(true);expect(f.effects).toHaveLength(0);}finally{await f.close();}});
it('changed resolved destination invalidates a waiting grant',async()=>{const f=await fixture();try{const c=f.invoke(),p=await f.request();f.target('different-ledger');expect(()=>f.policy.decide(decisionFor(p,'allow-once'))).toThrow();await c.result;expect(f.effects).toHaveLength(0);}finally{await f.close();}});
for(const change of ['arguments','call','turn','name','foreign','nested','root','duplicate'])it(`untrusted ${change} facts fail before body entry`,async()=>{const f=await fixture();try{const overrides:any={},fact:any={};if(change==='arguments')fact.arguments='{"label":"different"}';if(change==='call')overrides.callId=ToolCallId('missing');if(change==='turn')fact.turn=2;if(change==='name')fact.name='other';if(change==='foreign')overrides.agent={session:f.session};if(change==='nested')overrides.parent=Symbol();if(change==='root')overrides.rootCallId=ToolCallId('other');if(change==='duplicate')f.session.append('tool/call',{turn:1,step:1,callId:ToolCallId('c1'),name:f.definition.name,arguments:'{"label":"hello"}'});expect((await f.invoke('c1','hello',overrides,fact).result).isError).toBe(true);expect(f.frames.filter(x=>x.method==='wisp.approval.requested')).toHaveLength(0);expect(f.effects).toHaveLength(0);}finally{await f.close();}});
for(const mode of ['timeout','missing','throwing'])it(`${mode} answerer fails closed`,async()=>{const f=await fixture(10);try{if(mode==='missing')f.stopAnswering();if(mode==='throwing')f.ctx.on('approval/request',async()=>{if(mode==='throwing')throw Error('private');return 'unavailable' as const},{prepend:true});expect((await f.invoke().result).isError).toBe(true);expect(f.effects).toHaveLength(0);}finally{await f.close();}});
for(const timing of ['pending','allowed-unused','after-effect'])it(`cancellation ${timing} preserves honest effect boundary`,async()=>{const f=await fixture();try{const c=f.invoke(),p=await f.request();if(timing!=='pending')f.policy.decide(decisionFor(p,'allow-once'));if(timing==='after-effect')await c.result;c.c.abort();f.policy.cancel();await c.result;expect(f.effects).toHaveLength(timing==='after-effect'?1:0);expect(()=>f.policy.decide(decisionFor(p,'allow-once'))).toThrow();}finally{await f.close();}});
it('two actual registry requests stay distinct and overflow is rejected',async()=>{const f=await fixture();try{const calls=Array.from({length:9},(_,i)=>f.invoke('c'+i));await f.request(8);expect((await calls[8].result).isError).toBe(true);const requests=f.frames.filter(x=>x.method==='wisp.approval.requested').map(x=>x.params);f.policy.decide(decisionFor(requests[1],'allow-once'));f.policy.decide(decisionFor(requests[0],'deny'));await calls[1].result;f.policy.cancel();await Promise.all(calls.map(c=>c.result));expect(f.effects).toHaveLength(1);}finally{await f.close();}});
for(const name of ['mcp__unknown__send','skill','subagent','run_code','bash'])it(`unavailable ${name} route cannot execute`,async()=>{const f=await fixture();try{expect((await f.invoke('c1','hello',{name}).result).isError).toBe(true);expect(f.effects).toHaveLength(0);}finally{await f.close();}});
